name: Publish

on:
  push:
    tags: 
    - 'v*'

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/build

    - uses: smokedlinq/powershell-devops@v0

    - run: |
        Import-Module powershell-devops
        $Version = $($env:GITHUB_REF -replace '^refs/tags/v','')
        $IsPrerelease = $Version -like '*-*'
        Write-Host "Version: '$Version' | IsPrerelease: $IsPrerelease"
        Set-EnvironmentVariable PACKAGE_VERSION $Version
        Set-EnvironmentVariable IS_PRERELEASE $IsPrerelease
      shell: pwsh
      
    - run: dotnet pack --configuration Release -p:Version=$(PACKAGE_VERSION) --output ./publish

    - run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: ./publish

    - run: dotnet nuget push "*.nupkg" -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate --no-symbols true --api-key ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./publish

    - uses: actions/create-release@master
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: ${{ env.IS_PRERELEASE }}
